# cabal methods based on https://github.com/haskell-CI/haskell-ci
# run with: stack runghc -- ../haskell-ci/make_travis_yml_2.hs tidal.cabal > .travis-cabal.yml
# stack methods based on https://raw.githubusercontent.com/commercialhaskell/stack/stable/doc/travis-complex.yml

language: haskell
dist: trusty

cache:
  directories:
    - $HOME/.cabal/packages
    - $HOME/.cabal/store
    - $HOME/.stack
    - $TRAVIS_BUILD_DIR/.stack-work

cabal: "2.4"

matrix:
  include:
    - env: BUILD=cabal GHCVER=8.6.3
      ghc: "8.6.3"
    - env: BUILD=cabal GHCVER=8.4.4
      ghc: "8.4.4"
    - env: BUILD=cabal GHCVER=8.2.2
      ghc: "8.2.2"
    - env: BUILD=cabal GHCVER=8.0.2
      ghc: "8.0.2"
    - env: BUILD=cabal GHCVER=7.10.3
      ghc: "7.10.3"
    - env: BUILD=stack ARGS="--resolver lts-12.22 --system-ghc"
      ghc: "8.4.4"
    - env: BUILD=stack-wall ARGS="--resolver lts-12.22 --system-ghc"
      ghc: "8.4.4"
    - env: BUILD=stack ARGS="--resolver nightly --system-ghc"
      ghc: "8.6.2"

  allow_failures:
    - env: BUILD=stack-wall ARGS="--resolver lts-12.22 --system-ghc"
    - env: BUILD=stack ARGS="--resolver nightly --system-ghc"

install:
- |
  case "$BUILD" in
    cabal)
      cabal --version
      ghc --version
      ;;
    stack|stack-wall)
      ghc --version
      if [ `uname` = "Darwin" ]
      then
        travis_retry curl --insecure -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
      else
        travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      fi
      ;;
  esac

script:
- |
  case "$BUILD" in
    cabal)
      cabal v2-update
      cabal v2-build
      cabal v2-test --enable-test
      ;;
    stack)
      stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
      ;;
    stack-wall)
      # not sure whether passing -Werror etc with -only-dependencies was benign or not, hence separate $BUILD for stack-wall
      stack --no-terminal $ARGS build --bench --no-run-benchmarks --haddock --no-haddock-deps --ghc-options -Werror --ghc-options -Wall --ghc-options -Wcompat --ghc-options -Wincomplete-record-updates --ghc-options -Wincomplete-uni-patterns --ghc-options -Wredundant-constraints
      stack --no-terminal $ARGS test
      ;;
  esac
