# cabal methods based on https://github.com/haskell-CI/haskell-ci
# run with: stack runghc -- ../haskell-ci/make_travis_yml_2.hs tidal.cabal > .travis-cabal.yml
# stack methods based on https://raw.githubusercontent.com/commercialhaskell/stack/stable/doc/travis-complex.yml

language: haskell
dist: trusty

cache:
  directories:
    - $HOME/.cabal/packages
    - $HOME/.cabal/store
    - $HOME/.stack
    - $TRAVIS_BUILD_DIR/.stack-work

cabal: "2.4"

matrix:
  include:
    - env: BUILD=cabal-old GHCVER=8.6.3
      ghc: "8.6.3"
    - env: BUILD=cabal GHCVER=8.6.3
      ghc: "8.6.3"
    - env: BUILD=cabal GHCVER=8.4.4
      ghc: "8.4.4"
    - env: BUILD=cabal GHCVER=8.2.2
      ghc: "8.2.2"
    - env: BUILD=cabal GHCVER=8.0.2
      ghc: "8.0.2"
    - env: BUILD=cabal GHCVER=7.10.3
      ghc: "7.10.3"
    - env: BUILD=stack ARGS="--resolver lts-12.22 --system-ghc"
      ghc: "8.4.4"
      addons: {apt: {packages: [libgmp-dev]}}
    - env: BUILD=stack ARGS="--resolver nightly --system-ghc"
      ghc: "8.6.3"
      addons: {apt: {packages: [libgmp-dev]}}

  allow_failures:
    - env: BUILD=stack ARGS="--resolver nightly --system-ghc"
    - env: BUILD=cabal GHCVER=8.6.3

install:
- cabal --version
- ghc --version
- |
  case "$BUILD" in
    cabal)
      ;;
    cabal-old)
      ;;
    stack)
      PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$HOME/.cabal/bin:$PATH
      mkdir -p ~/.local/bin
      if [ `uname` = "Darwin" ]
      then
        travis_retry curl --insecure -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
      else
        travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      fi
      ;;
  esac

script:
- |
  case "$BUILD" in
    cabal)
      cabal v2-update
      cabal v2-build
      cabal v2-test --enable-test
      ;;
    cabal-old)
      cabal update
      cabal build
      cabal test
      ;;
    stack)
      stack --no-terminal $ARGS test --bench --only-dependencies
      stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
      ;;
  esac
